name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event
        run: echo '${{ toJSON(github.event) }}'
      - uses: actions/checkout@v3
      - uses: ./
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          tenantId: ${{ secrets.TENANT_ID }}
          planId: ${{ secrets.PLAN_ID }}
          title: "Review pull request."
          userId: "73ebbe8e-be1f-464d-847a-855598310a7d"
          bucketId: "Ys2XyYjrnkCQDmOZEJ8KDZcADKs9"
          dueBy: ${{'2023-01-29T10:00:00Z'}}
          description: "A new PR has been submitted on ${{ github.repository }} from ${{ github.actor }}."
          priority: "1"
